# Generated by Django 3.0.8 on 2020-07-30 17:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200730_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=30, validators=[users.models.email_validator]),
        ),
    ]
